---
- name: "Files dir should exist"
  file:
    path: "{{playbook_dir}}/files"
    state: directory
- name: "files csr dir should exist"
  file:
    path: "{{playbook_dir}}/files/csr"
    state: directory
- name: "secure dir should exist"
  file:
    path: "{{playbook_dir}}/files/secure"
    state: directory
    mode: "0700"
- name: Create ca-config.json
  template:
    src: ca-config.json.j2
    dest: "{{playbook_dir}}/files/csr/ca-config.json"
- name: Create ca-csr.json
  template:
    src: generic-csr.json.j2
    dest: "{{playbook_dir}}/files/csr/ca-csr.json"
  vars:
    csr_CN: "Kubernetes"
    csr_O: "Kubernetes"
- name: Gen CA Cert
  shell:
    cmd: |
      cfssl gencert -initca ../csr/ca-csr.json | cfssljson -bare ca
    chdir: "{{playbook_dir}}/files/secure"
    creates: "{{playbook_dir}}/files/secure/ca.pem"

- name: create admin-csr.json
  template:
    src: generic-csr.json.j2
    dest: "{{playbook_dir}}/files/csr/admin-csr.json"
  vars:
    csr_CN: "admin"
    csr_O: "system:masters"
- name: Gen Admin Cert
  shell:
    cmd: >
      cfssl gencert
      -ca=ca.pem
      -ca-key=ca-key.pem
      -config=../csr/ca-config.json
      -profile=kubernetes
      ../csr/admin-csr.json | cfssljson -bare admin
    chdir: "{{playbook_dir}}/files/secure"
    creates: "{{playbook_dir}}/files/secure/admin.pem"

- name: create worker csrs
  template:
    src: generic-csr.json.j2
    dest: "{{playbook_dir}}/files/csr/worker-{{item}}-csr.json"
  vars:
    csr_CN: "system:node:{{item}}"  # TODO: does this break?
    csr_O: "system:nodes"
  with_items:
    - "0"
    - "1"
    - "2"
- name: Gen Worker Certs
  shell:
    cmd: >-
      cfssl gencert
      -ca=ca.pem
      -ca-key=ca-key.pem
      -config=../csr/ca-config.json
      -hostname=worker-{{item}},{{hostvars["worker-"+item].public_ip}},{{hostvars["worker-"+item].internal_ip}}
      -profile=kubernetes
      ../csr/worker-{{item}}-csr.json | cfssljson -bare worker-{{item}}
    chdir: "{{playbook_dir}}/files/secure"
    creates: "{{playbook_dir}}/files/secure/worker-{{item}}.pem"
  loop:
    - "0"
    - "1"
    - "2"

- name: create controller manager client csr
  template:
    src: generic-csr.json.j2
    dest: "{{playbook_dir}}/files/csr/kube-controller-manager-csr.json"
  vars:
    csr_CN: "system:kube-controller-manager"
    csr_O: "system:kube-controller-manager"
- name: Gen Controller Manager Client Certificate
  shell:
    cmd: >
      cfssl gencert
      -ca=ca.pem
      -ca-key=ca-key.pem
      -config=../csr/ca-config.json
      -profile=kubernetes
      ../csr/kube-controller-manager-csr.json | cfssljson -bare kube-controller-manager
    chdir: "{{playbook_dir}}/files/secure"
    creates: "{{playbook_dir}}/files/secure/kube-controller-manager.pem"


- name: create kube proxy client csr
  template:
    src: generic-csr.json.j2
    dest: "{{playbook_dir}}/files/csr/kube-proxy-csr.json"
  vars:
    csr_CN: "system:kube-proxy"
    csr_O: "system:node-proxier"
- name: Gen Kube Proxy Client Certificate
  shell:
    cmd: >
      cfssl gencert
      -ca=ca.pem
      -ca-key=ca-key.pem
      -config=../csr/ca-config.json
      -profile=kubernetes
      ../csr/kube-proxy-csr.json | cfssljson -bare kube-proxy
    chdir: "{{playbook_dir}}/files/secure"
    creates: "{{playbook_dir}}/files/secure/kube-proxy.pem"

- name: create scheduler client csr
  template:
    src: generic-csr.json.j2
    dest: "{{playbook_dir}}/files/csr/kube-scheduler-csr.json"
  vars:
    csr_CN: "system:kube-scheduler"
    csr_O: "system:kube-scheduler"
- name: Gen Scheduler Client Certificate
  shell:
    cmd: >
      cfssl gencert
      -ca=ca.pem
      -ca-key=ca-key.pem
      -config=../csr/ca-config.json
      -profile=kubernetes
      ../csr/kube-scheduler-csr.json | cfssljson -bare kube-scheduler
    chdir: "{{playbook_dir}}/files/secure"
    creates: "{{playbook_dir}}/files/secure/kube-scheduler.pem"

- name: create api server csr
  template:
    src: generic-csr.json.j2
    dest: "{{playbook_dir}}/files/csr/kubernetes-csr.json"
  vars:
    csr_CN: "kubernetes"
    csr_O: "Kubernetes"
- name: Gen Kubernetes API Server Certificate
  shell:
    cmd: >
      cfssl gencert
      -ca=ca.pem
      -ca-key=ca-key.pem
      -config=../csr/ca-config.json
      -hostname=10.32.0.1,10.240.0.10,10.240.0.11,10.240.0.12,{{kubernetes_public_address}},127.0.0.1,{{kubernetes_hostnames}}
      -profile=kubernetes
      ../csr/kubernetes-csr.json | cfssljson -bare kubernetes
    chdir: "{{playbook_dir}}/files/secure"
    creates: "{{playbook_dir}}/files/secure/kubernetes.pem"
  vars:
    # kubernetes_public_address generated by tf ansible_resources.tf to group_vars/all/kubernetes_public_address.yml
    kubernetes_hostnames: "kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.svc.cluster.local"

- name: create service account csr
  template:
    src: generic-csr.json.j2
    dest: "{{playbook_dir}}/files/csr/service-account-csr.json"
  vars:
    csr_CN: service-accounts
    csr_O: Kubernetes
- name: Gen Service Account Certificate
  shell:
    cmd: >
      cfssl gencert
      -ca=ca.pem
      -ca-key=ca-key.pem
      -config=../csr/ca-config.json
      -profile=kubernetes
      ../csr/service-account-csr.json | cfssljson -bare service-account
    chdir: "{{playbook_dir}}/files/secure"
    creates: "{{playbook_dir}}/files/secure/service-account.pem"
