---
- name: get kubectl component statuses
  command:
    cmd: kubectl cluster-info --kubeconfig admin.kubeconfig
  register: cluster_info

- name: debug component statuses
  debug:
    msg: "{{cluster_info}}"

- name: validate that component statuses are green
  assert:
    that:
      - 'cluster_info.stdout is search("Kubernetes control plan is running at")'

- name: curl the healthz endpoint
  command: "curl -H 'Host: kubernetes.default.svc.cluster.local' -i http://127.0.0.1/healthz"
  register: healthz_curl

- name: "debug curl output"
  debug:
    msg: "{{healthz_curl}}"

- name: validate the curl response
  assert:
    that:
      - 'healthz_curl.stdout is search("200 OK")'
