# reference https://wiki.archlinux.org/title/systemd-networkd#network_files
- name: add pod-routes.network systemd network file
  become: yes
  template:
    src: pod-routes.network.j2
    dest: /etc/systemd/network/pod-routes.{{hostvars[item].inventory_hostname}}.network
  loop: '{{groups["workers"]}}'

- name: Load latest network configurations
  become: yes
  systemd:
    name: systemd-networkd.service
    state: restarted
    enabled: yes
    daemon_reload: true
