- name: Set routes
  become: yes
  command: "ip route replace {{hostvars[item].pod_cidr}} via {{hostvars[item].internal_ip}}"
  loop: '{{groups["workers"]}}'

- name: Add hosts entries for worker hosts
  become: yes
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      {% for worker in groups["workers"] %}
      {{hostvars[worker].internal_ip}} {{hostvars[worker].inventory_hostname}}
      {% endfor %}

## reference https://wiki.archlinux.org/title/systemd-networkd#network_files
#- name: add pod-routes.network systemd network file
#  become: yes
#  template:
#    src: pod-routes.network.j2
#    dest: /etc/systemd/network/pod-routes.{{hostvars[item].inventory_hostname}}.network
#  loop: '{{groups["workers"]}}'
#
#- name: Load latest network configurations
#  become: yes
#  systemd:
#    name: systemd-networkd.service
#    state: restarted
#    enabled: yes
#    daemon_reload: true
