---
- name: install nginx
  apt:
    name: nginx
    state: present

- name: config nginx sites available
  template:
    src: kubernetes.default.svc.cluster.local.j2
    dest: /etc/nginx/sites-available/kubernetes.default.svc.cluster.local
    owner: root
    group: root
    mode: "644"

- name: set nginx sites as enabled
  file:
    state: link
    src: /etc/nginx/sites-available/kubernetes.default.svc.cluster.local
    path: /etc/nginx/sites-enabled/kubernetes.default.svc.cluster.local

- name: enabled and (re)start nginx
  systemd:
    name: nginx
    enabled: true
    state: restarted
