---
- name: install nginx
  apt:
    name: nginx
    state: installed

- name: config nginx sites available
  template:
    src: kubernetes.default.svc.cluster.local.j2
    dest: /etc/nginx/sites-available/kubernetes.default.svc.cluster.local
    owner: root
    group: root
    mode: "644"

- name: enabled and (re)start nginx
  systemd:
    name: nginx
    enabled: true
    state: restarted
